# Configures Baci tests at Travis CI (https://travis-ci.org).

language: go

go:
 - 1.3
 - 1.4

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y realpath

install:
 - go get code.google.com/p/go.tools/cmd/cover
 - go get code.google.com/p/go.tools/cmd/vet

script:
 - ./test

